# Enter your zone id and account id, then rename this file to wrangler.toml.
# Consider removing wrangler.toml from the .gitignore file
compatibility_date = "2021-11-25"
name = "project-name"
workers_dev = true
main = "src/index.ts"

[build]
command = "npm run build:nocleanup"

